[package]
name = "rzoo"
version = "0.1.0"
authors = ["Arttu Valo <arttu.valo@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.2"

[dev-dependencies]
pretty_assertions = "0.6.1"
